name: Build and Release Workflow
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Compilation
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: classes
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Unit tests
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: test
      - name: Integration tests
        uses: eskatos/gradle-command-action@v1
        with:
         arguments: integrationTest
      - name: Functional tests
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: functionalTest
      - name: Documentation tests
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: docTest
  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Upload binaries
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: assemble bintrayUpload -s
      - name: Publish documentation
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: gitPublishPush -Dorg.ajoberstar.grgit.auth.username=${{ secrets.GITHUB_TOKEN }} -s